spring:
  application:
    name: A-AND-I-DISCORD-BOT
  main:
    web-application-type: none
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul

discord:
  enabled: ${DISCORD_ENABLED:true}
  token: ${DISCORD_TOKEN}
  guild-id: ${DISCORD_GUILD_ID}

app:
  timezone: Asia/Seoul

logging:
  level:
    net.dv8tion.jda: INFO
